[tools]
# always languages
python = ["3.12"]
node = "lts"
go = "1.22"

# global node-based npm tools
"npm:tldr" = "latest"
"npm:trash-cli" = "latest"
"npm:epub-wordcount" = "latest"
"npm:will-it-play" = "latest"
"npm:yarn" = "latest"
uv = "latest"
deno = "latest"                 # for yt-dlp

[settings]
# needed for npm packages
experimental = true

[settings.status]
missing_tools = "always"
